import { useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Loader from "../components/Loader";
import styles from "../styles/Home.module.css";
import Dashboard from "./Dashboard";

export default function Home() {
  const router = useRouter();
  const { session: data, status } = useSession({
    onUnauthenticated() {
      router.push("/auth/signin");
    },
  });
  if (status === "loading") return <Loader />;
  return (
    <div>
      <Head>
        <title>Spotify - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
    </div>
  );
}
